<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Orbyss.ProgramKit.Artifacts" Version="0.1.0-alpha.1" />
    <PackageVersion Include="Orbyss.ProgramKit.Serialization.JSON" Version="0.1.0-alpha.1" />
  </ItemGroup>
</Project>
