// <auto-generated program-kit>
using CShells.Configuration;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using CShells.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace GeneratedHost.Composition;

internal static partial class Program
{
    private static async Task<int> Main(string[] args)
    {
var parseResult = GeneratedHost.Commands.GeneratedConsoleParser.Parse(args);
if (!parseResult.Success)
{
    global::System.Console.Error.WriteLine(parseResult.Diagnostic);
    return parseResult.ExitCode;
}
if (!parseResult.InvokeCommand)
{
    global::System.Console.Out.WriteLine(parseResult.Output);
    return parseResult.ExitCode;
}

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddCShells(cshells =>
{
    cshells.AddShell("pkid:shell:jtest:cli", shell =>
    {
    });
});
ConfigureProgramKitConsoleServices(builder.Services);
using var host = builder.Build();
var dispatchers = host.Services
    .GetServices<GeneratedHost.Commands.IProgramKitConsoleCommandDispatcher>()
    .ToArray();
if (dispatchers.Length != 1)
{
    throw new InvalidOperationException(
        "Exactly one IProgramKitConsoleCommandDispatcher registration is required.");
}
var dispatcher = dispatchers[0];
var applicationLifetime = host.Services.GetRequiredService<
    global::Microsoft.Extensions.Hosting.IHostApplicationLifetime>();
try
{
    await host.StartAsync();
    return await dispatcher.DispatchAsync(
        parseResult,
        applicationLifetime.ApplicationStopping);
}
finally
{
    using var stopCancellation = new CancellationTokenSource(
        TimeSpan.FromSeconds(30));
    await host.StopAsync(stopCancellation.Token);
}
    }

    static partial void ConfigureProgramKitConsoleServices(
        IServiceCollection services);
}
