// <auto-generated program-kit>
using System.Globalization;

namespace GeneratedHost.Commands;

internal static class GeneratedConsoleParser
{
    private static readonly (string[] Path, string Command)[] CommandPaths =
    [
        (["describe"], "describe"),
        (["run"], "run"),
        (["validate"], "validate"),
    ];

    private static string NormalizeOption(string value) =>
        value switch
        {
            "--diagnostics" => "diagnostics",
            "--env" => "env",
            "-e" => "env",
            "--env-file" => "env-file",
            "--globals-file" => "globals-file",
            "--no-open" => "no-open",
            "--open" => "open",
            "--output" => "output",
            "--parallel" => "parallel",
            "-p" => "parallel",
            "--report" => "report",
            "--report-dir" => "report-dir",
            "--report-out" => "report-out",
            "--schema" => "schema",
            "--secret-env" => "secret-env",
            "--timeout" => "timeout",
            _ => string.Empty,
        };

    internal static GeneratedConsoleParseResult Parse(string[] args)
    {
        ArgumentNullException.ThrowIfNull(args);
        if (TryRenderInformation(args, out var information))
        {
            return information;
        }

        var command = ResolveCommand(args, out var commandTokens);
        if (command.Length == 0)
        {
            return Failure("PKNETC001 A known command path is required.", 2);
        }

        var options = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        var occurrences = new Dictionary<string, int>(StringComparer.Ordinal);
        var arguments = new List<string>();
        var terminated = false;
        for (var index = commandTokens; index < args.Length; index++)
        {
            var token = args[index];
            if (!terminated && token == "--")
            {
                terminated = true;
                continue;
            }

            if (!terminated && token.StartsWith('-'))
            {
                var separator = token.IndexOf('=');
                var name = separator < 0 ? token : token[..separator];
                var canonical = NormalizeOption(name);
                if (canonical.Length == 0 || !IsAllowed(command, canonical))
                {
                    return Failure(string.Concat("PKNETC002 Unknown option: ", name), 2);
                }

                occurrences.TryGetValue(canonical, out var occurrence);
                if (occurrence >= MaximumOccurrences(command, canonical))
                {
                    return Failure(string.Concat("PKNETC003 Option occurrence exceeded: ", canonical), 2);
                }

                occurrences[canonical] = occurrence + 1;
                if (!options.TryGetValue(canonical, out var values))
                {
                    values = [];
                    options.Add(canonical, values);
                }

                if (RequiresValue(command, canonical))
                {
                    var occurrenceValues = new List<string>();
                    if (separator >= 0)
                    {
                        occurrenceValues.Add(token[(separator + 1)..]);
                    }
                    else
                    {
                        var maximumValues = MaximumValues(command, canonical);
                        while (occurrenceValues.Count < maximumValues && index + 1 < args.Length)
                        {
                            var candidate = args[index + 1];
                            var candidateSeparator = candidate.IndexOf('=');
                            var candidateName = candidateSeparator < 0 ? candidate : candidate[..candidateSeparator];
                            if (candidate == "--" || NormalizeOption(candidateName).Length != 0)
                            {
                                break;
                            }

                            occurrenceValues.Add(candidate);
                            index++;
                        }
                    }

                    if (occurrenceValues.Count < MinimumValues(command, canonical) ||
                        occurrenceValues.Count > MaximumValues(command, canonical) ||
                        occurrenceValues.Any(value => string.IsNullOrEmpty(value) || !HasValidType(command, canonical, value)))
                    {
                        return Failure(string.Concat("PKNETC004 Invalid option value: ", canonical), 2);
                    }

                    values.AddRange(occurrenceValues);
                }
                else
                {
                    values.Add("true");
                }

                continue;
            }

            arguments.Add(token);
        }

        ApplyDefaults(command, options, occurrences);
        var contractDiagnostic = ValidateContract(command, options, arguments);
        if (contractDiagnostic.Length != 0)
        {
            return Failure(contractDiagnostic, 2);
        }

        var readOnly = options.ToDictionary(
            static pair => pair.Key,
            static pair => (IReadOnlyList<string>)pair.Value,
            StringComparer.Ordinal);
        return new GeneratedConsoleParseResult(true, true, 0, string.Empty, string.Empty, command, readOnly, arguments);
    }

    private static readonly string[] CompletionCandidates =
    [
        "--diagnostics",
        "--diagnostics=<string>",
        "--env",
        "--env-file",
        "--env-file=<string>",
        "--env=<string>",
        "--globals-file",
        "--globals-file=<string>",
        "--no-open",
        "--open",
        "--output",
        "--output=<string>",
        "--parallel",
        "--parallel=<string>",
        "--report",
        "--report-dir",
        "--report-dir=<string>",
        "--report-out",
        "--report-out=<string>",
        "--report=<string>",
        "--schema",
        "--schema=<string>",
        "--secret-env",
        "--secret-env=<string>",
        "--timeout",
        "--timeout=<string>",
        "-e",
        "-p",
        "describe",
        "run",
        "validate",
    ];

    private static bool TryRenderInformation(
        string[] args,
        out GeneratedConsoleParseResult result)
    {
        var completionIndex = Array.IndexOf(args, "--complete");
        if (completionIndex >= 0)
        {
            var prefix = completionIndex + 1 < args.Length ? args[completionIndex + 1] : string.Empty;
            var output = string.Join(Environment.NewLine, CompletionCandidates.Where(candidate => candidate.StartsWith(prefix, StringComparison.Ordinal)));
            result = Information(string.Empty, output, 0);
            return true;
        }

        var helpIndex = Array.FindIndex(args, token =>
            token == "--help" || token == "-h");
        if (helpIndex >= 0)
        {
            var command = ResolveCommand(args, out _);
            result = Information(command, RenderHelp(command), 0);
            return true;
        }

        result = default!;
        return false;
    }

    private static string RenderHelp(string command) =>
        command switch
        {
            "describe" => "Usage: describe\r\nEmits the agent-facing language manifest or an exact published schema.\r\nOptions:\r\n  --output  Target file path, or - for standard output.\r\n  --schema  Artifact to emit: manifest, suite, templates, or result.\r\nExit codes:\r\n  0  Every discovered suite produced a complete passing trace.\r\n  1  At least one case failed, errored, timed out, or was cancelled.\r\n  2  Usage, input, discovery, or validation failure.\r\n  3  Unexpected internal failure.",
            "run" => "Usage: run <patterns>\r\nExecutes suites and writes truthful reports; the exit code is computed from the canonical evidence.\r\nOptions:\r\n  --diagnostics  Diagnostic output format: text or json.\r\n  --env, -e  Environment value as key=value; repeatable.\r\n  --env-file  Path of a JSON object file merged into env (CLI wins).\r\n  --globals-file  Path of a JSON object file merged into globals (CLI wins).\r\n  --no-open  Suppress opening the report page.\r\n  --open  Force opening the report page.\r\n  --parallel, -p  Maximum suites executed concurrently.\r\n  --report  Report mode: catalog (default) or standalone.\r\n  --report-dir  Catalog reports directory (default .jtest/reports).\r\n  --report-out  Standalone report output directory.\r\n  --secret-env  Name of a CLI env entry whose value is redacted in evidence; repeatable.\r\n  --timeout  Overall run timeout in milliseconds.\r\nExit codes:\r\n  0  Every discovered suite produced a complete passing trace.\r\n  1  At least one case failed, errored, timed out, or was cancelled.\r\n  2  Usage, input, discovery, or validation failure.\r\n  3  Unexpected internal failure.",
            "validate" => "Usage: validate <patterns>\r\nValidates suites and prints machine-readable diagnostics without executing anything.\r\nOptions:\r\n  --diagnostics  Diagnostic output format: text or json.\r\nExit codes:\r\n  0  Every discovered suite produced a complete passing trace.\r\n  1  At least one case failed, errored, timed out, or was cancelled.\r\n  2  Usage, input, discovery, or validation failure.\r\n  3  Unexpected internal failure.",
            _ => "jtest 2.0.0\r\nDeclarative JSON end-to-end API tests: run, validate, and describe.\r\n\r\nCommands:\r\n  describe  Emits the agent-facing language manifest or an exact published schema.\r\n  run  Executes suites and writes truthful reports; the exit code is computed from the canonical evidence.\r\n  validate  Validates suites and prints machine-readable diagnostics without executing anything.\r\n\r\nUse --help after a command for command help.",
        };

    private static GeneratedConsoleParseResult Information(
        string command,
        string output,
        int exitCode) =>
        new(true, false, exitCode, string.Empty, output, command, new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal), []);

    private static string ResolveCommand(string[] args, out int consumed)
    {
        foreach (var candidate in CommandPaths)
        {
            if (args.Length >= candidate.Path.Length &&
                candidate.Path.Where((part, index) => args[index] == part).Count() == candidate.Path.Length)
            {
                consumed = candidate.Path.Length;
                return candidate.Command;
            }
        }

        consumed = 0;
        return string.Empty;
    }

    private static bool IsAllowed(string command, string option) =>
        string.Concat(command, "\u001f", option) switch
        {
            "describeschema" => true,
            "describeoutput" => true,
            "runenv-file" => true,
            "runenv" => true,
            "runglobals-file" => true,
            "runsecret-env" => true,
            "runreport" => true,
            "runreport-dir" => true,
            "runreport-out" => true,
            "runparallel" => true,
            "runtimeout" => true,
            "runopen" => true,
            "runno-open" => true,
            "rundiagnostics" => true,
            "validatediagnostics" => true,
            _ => false,
        };

    private static bool RequiresValue(string command, string option) =>
        string.Concat(command, "\u001f", option) switch
        {
            "describeschema" => true,
            "describeoutput" => true,
            "runenv-file" => true,
            "runenv" => true,
            "runglobals-file" => true,
            "runsecret-env" => true,
            "runreport" => true,
            "runreport-dir" => true,
            "runreport-out" => true,
            "runparallel" => true,
            "runtimeout" => true,
            "runopen" => false,
            "runno-open" => false,
            "rundiagnostics" => true,
            "validatediagnostics" => true,
            _ => false,
        };

    private static int MinimumValues(string command, string option) =>
        string.Concat(command, "\u001f", option) switch
        {
            "describeschema" => 1,
            "describeoutput" => 1,
            "runenv-file" => 1,
            "runenv" => 1,
            "runglobals-file" => 1,
            "runsecret-env" => 1,
            "runreport" => 1,
            "runreport-dir" => 1,
            "runreport-out" => 1,
            "runparallel" => 1,
            "runtimeout" => 1,
            "runopen" => 0,
            "runno-open" => 0,
            "rundiagnostics" => 1,
            "validatediagnostics" => 1,
            _ => 0,
        };

    private static int MaximumValues(string command, string option) =>
        string.Concat(command, "\u001f", option) switch
        {
            "describeschema" => 1,
            "describeoutput" => 1,
            "runenv-file" => 1,
            "runenv" => 1,
            "runglobals-file" => 1,
            "runsecret-env" => 1,
            "runreport" => 1,
            "runreport-dir" => 1,
            "runreport-out" => 1,
            "runparallel" => 1,
            "runtimeout" => 1,
            "runopen" => 0,
            "runno-open" => 0,
            "rundiagnostics" => 1,
            "validatediagnostics" => 1,
            _ => 0,
        };

    private static int MaximumOccurrences(string command, string option) =>
        string.Concat(command, "\u001f", option) switch
        {
            "describeschema" => 1,
            "describeoutput" => 1,
            "runenv-file" => 1,
            "runenv" => 64,
            "runglobals-file" => 1,
            "runsecret-env" => 64,
            "runreport" => 1,
            "runreport-dir" => 1,
            "runreport-out" => 1,
            "runparallel" => 1,
            "runtimeout" => 1,
            "runopen" => 1,
            "runno-open" => 1,
            "rundiagnostics" => 1,
            "validatediagnostics" => 1,
            _ => 0,
        };

    private static bool HasValidType(string command, string option, string value)
        => HasValidValueType(ValueType(command, option), value);

    private static bool HasValidValueType(string type, string value)
    {
        return type switch
        {
            "string" => true,
            "boolean" => bool.TryParse(value, out _),
            "int32" => int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out _),
            "int64" => long.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out _),
            "decimal" => decimal.TryParse(value, NumberStyles.Number, CultureInfo.InvariantCulture, out _),
            "guid" => Guid.TryParseExact(value, "D", out _),
            "date-time" => DateTimeOffset.TryParseExact(value, "O", CultureInfo.InvariantCulture, DateTimeStyles.None, out _),
            _ => false,
        };
    }

    private static string ValueType(string command, string option) =>
        string.Concat(command, "\u001f", option) switch
        {
            "describeschema" => "string",
            "describeoutput" => "string",
            "runenv-file" => "string",
            "runenv" => "string",
            "runglobals-file" => "string",
            "runsecret-env" => "string",
            "runreport" => "string",
            "runreport-dir" => "string",
            "runreport-out" => "string",
            "runparallel" => "string",
            "runtimeout" => "string",
            "runopen" => "boolean",
            "runno-open" => "boolean",
            "rundiagnostics" => "string",
            "validatediagnostics" => "string",
            _ => string.Empty,
        };

    private static void ApplyDefaults(
        string command,
        Dictionary<string, List<string>> options,
        Dictionary<string, int> occurrences)
    {
        switch (command)
        {
            case "describe":
            {
                if (!options.ContainsKey("schema"))
                {
                    options.Add("schema", ["manifest"]);
                    occurrences.TryAdd("schema", 0);
                }
                if (!options.ContainsKey("output"))
                {
                    options.Add("output", ["-"]);
                    occurrences.TryAdd("output", 0);
                }
                break;
            }
            case "run":
            {
                if (!options.ContainsKey("report"))
                {
                    options.Add("report", ["catalog"]);
                    occurrences.TryAdd("report", 0);
                }
                if (!options.ContainsKey("parallel"))
                {
                    options.Add("parallel", ["1"]);
                    occurrences.TryAdd("parallel", 0);
                }
                if (!options.ContainsKey("diagnostics"))
                {
                    options.Add("diagnostics", ["text"]);
                    occurrences.TryAdd("diagnostics", 0);
                }
                break;
            }
            case "validate":
            {
                if (!options.ContainsKey("diagnostics"))
                {
                    options.Add("diagnostics", ["text"]);
                    occurrences.TryAdd("diagnostics", 0);
                }
                break;
            }
        }
    }

    private static string ValidateContract(
        string command,
        Dictionary<string, List<string>> options,
        List<string> arguments)
    {
        switch (command)
        {
            case "describe":
            {
                if (arguments.Count is < 0 or > 0)
                    return "PKNETC008 Positional argument arity is invalid.";
                var argumentIndex = 0;
                if (argumentIndex != arguments.Count)
                    return "PKNETC008 Positional argument arity is invalid.";
                break;
            }
            case "run":
            {
                if (arguments.Count is < 1 or > 64)
                    return "PKNETC008 Positional argument arity is invalid.";
                var argumentIndex = 0;
                var argumentCount0 = Math.Min(64, Math.Max(1, arguments.Count - argumentIndex - 0));
                for (var offset = 0; offset < argumentCount0; offset++)
                {
                    if (!HasValidValueType("string", arguments[argumentIndex + offset]))
                        return "PKNETC009 Invalid positional argument value: patterns";
                }
                argumentIndex += argumentCount0;
                if (argumentIndex != arguments.Count)
                    return "PKNETC008 Positional argument arity is invalid.";
                break;
            }
            case "validate":
            {
                if (arguments.Count is < 1 or > 64)
                    return "PKNETC008 Positional argument arity is invalid.";
                var argumentIndex = 0;
                var argumentCount0 = Math.Min(64, Math.Max(1, arguments.Count - argumentIndex - 0));
                for (var offset = 0; offset < argumentCount0; offset++)
                {
                    if (!HasValidValueType("string", arguments[argumentIndex + offset]))
                        return "PKNETC009 Invalid positional argument value: patterns";
                }
                argumentIndex += argumentCount0;
                if (argumentIndex != arguments.Count)
                    return "PKNETC008 Positional argument arity is invalid.";
                break;
            }
        }

        return string.Empty;
    }

    private static GeneratedConsoleParseResult Failure(string diagnostic, int exitCode) =>
        new(false, false, exitCode, diagnostic, string.Empty, string.Empty, new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal), []);
}
