// <auto-generated program-kit>
namespace GeneratedHost.Commands;

internal sealed record GeneratedConsoleParseResult(
    bool Success,
    bool InvokeCommand,
    int ExitCode,
    string Diagnostic,
    string Output,
    string Command,
    IReadOnlyDictionary<string, IReadOnlyList<string>> Options,
    IReadOnlyList<string> Arguments);