// <auto-generated program-kit>
namespace GeneratedHost.Commands;

internal interface IProgramKitConsoleCommandDispatcher
{
    ValueTask<int> DispatchAsync(
        GeneratedConsoleParseResult parseResult,
        CancellationToken cancellationToken);
}
